#! /bin/bash

EXPECTED_ARGS=1
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: `basename $0` LOGFILE"
  echo "Parse a log file generated by ./bcclient and find number"
  echo "of bitcoin peers to which we successfully connected (i.e."
  echo "exchanged 'version' messages)"
  exit $E_BADARGS
fi

log_file="$1"

result=$(grep "Version received" $log_file  | cut -f8 -d ' ' | cut -f2 -d'=' | tr -d ',' | sort -u | sed -r 's/(:[0-9]+)\.[0-9]+/\1/g' | sort | uniq -c)
total_connections=$(echo -e "$result" | tr -s ' ' | cut -f2 -d ' ' | paste -s -d+ | bc)

echo -n "Number of connected IP addresses: "
#echo $(tput setaf 1)$(tput bold)$(echo -e "$result" | wc -l)$(tput sgr0)
echo $(echo -e "$result" | wc -l)
echo -n "Total number of connections: "
#echo -e "$(tput setaf 1)$(tput bold)$total_connections$(tput sgr0)"
echo -e "$total_connections"
echo "Number of connections per IP address: "
echo -e "$result"
